import { PDFDocument, rgb, StandardFonts } from 'pdf-lib'

export async function generateReceiptPDF({ memberName, paidBy, storeName, receiptCode, date, items, total, isSelf }) {
  const doc = await PDFDocument.create()
  const page = doc.addPage([480, 680])
  const { width, height } = page.getSize()

  const bold = await doc.embedFont(StandardFonts.HelveticaBold)
  const regular = await doc.embedFont(StandardFonts.Helvetica)

  const purple = rgb(0.49, 0.23, 0.93)
  const dark = rgb(0.1, 0.1, 0.1)
  const gray = rgb(0.45, 0.45, 0.45)
  const light = rgb(0.9, 0.9, 0.95)
  const white = rgb(1, 1, 1)

  let y = height - 40

  // Header background strip
  page.drawRectangle({ x: 0, y: height - 90, width, height: 90, color: purple })

  // App name
  page.drawText('SPLITS', { x: 30, y: height - 30, size: 11, font: bold, color: white, letterSpacing: 4 })

  // Store name / title
  const title = storeName || `Receipt #${receiptCode}`
  page.drawText(title, { x: 30, y: height - 52, size: 20, font: bold, color: white })
  page.drawText(`#${receiptCode}`, { x: 30, y: height - 70, size: 9, font: regular, color: rgb(0.8, 0.75, 1) })

  y = height - 110

  // Date + Paid by
  const dateStr = date ? new Date(date).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }) : ''
  page.drawText(dateStr, { x: 30, y, size: 9, font: regular, color: gray })
  page.drawText(`Paid by: ${paidBy}`, { x: 30, y: y - 14, size: 9, font: regular, color: gray })

  y -= 44

  // "Your items" header
  page.drawRectangle({ x: 0, y: y - 4, width, height: 22, color: light })
  page.drawText(`Your items, ${memberName}`, { x: 30, y: y + 2, size: 10, font: bold, color: purple })
  y -= 14

  // Column headers
  y -= 18
  page.drawText('ITEM', { x: 30, y, size: 8, font: bold, color: gray })
  page.drawText('FULL PRICE', { x: 240, y, size: 8, font: bold, color: gray })
  page.drawText('SPLIT WITH', { x: 318, y, size: 8, font: bold, color: gray })
  page.drawText('YOUR SHARE', { x: 400, y, size: 8, font: bold, color: gray })

  // Divider
  y -= 8
  page.drawLine({ start: { x: 30, y }, end: { x: width - 30, y }, thickness: 0.5, color: light })
  y -= 12

  // Items
  for (const item of items) {
    if (y < 100) break
    const shareStr = `$${item.share.toFixed(2)}`
    const priceStr = `$${item.price.toFixed(2)}`
    const splitStr = item.splitWith.join(', ')
    const splitDisplay = splitStr.length > 14 ? splitStr.slice(0, 13) + '…' : splitStr

    // Truncate item name
    const nameDisplay = item.name.length > 28 ? item.name.slice(0, 27) + '…' : item.name

    page.drawText(nameDisplay, { x: 30, y, size: 9, font: regular, color: dark })
    page.drawText(priceStr, { x: 240, y, size: 9, font: regular, color: dark })
    page.drawText(splitDisplay, { x: 318, y, size: 9, font: regular, color: gray })
    page.drawText(shareStr, { x: 400, y, size: 9, font: bold, color: purple })

    y -= 18

    page.drawLine({ start: { x: 30, y: y + 4 }, end: { x: width - 30, y: y + 4 }, thickness: 0.3, color: rgb(0.93, 0.93, 0.96) })
  }

  // Total row
  y -= 10
  page.drawRectangle({ x: 0, y: y - 8, width, height: 36, color: rgb(0.97, 0.95, 1) })
  const totalLabel = isSelf ? 'Total you covered' : `Total you owe ${paidBy}`
  page.drawText(totalLabel, { x: 30, y: y + 6, size: 10, font: bold, color: dark })
  page.drawText(`$${total.toFixed(2)}`, { x: 400, y: y + 6, size: 13, font: bold, color: purple })

  // Footer
  y -= 40
  page.drawText('Generated by SPLITS · household receipt ledger', {
    x: 30, y: 30, size: 8, font: regular, color: rgb(0.7, 0.7, 0.75),
  })

  return await doc.save()
}
